use anyhow::Error;

pub async fn main() -> Result<(), Error>{
    let stdin = std::io::stdin();
    
}